spring:
  application:
    name: ecommerce-platform
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce_db
    username: myuser
    password: fialka
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: user_management
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    schemas: user_management

server:
  port: 8080

application:
  security:
    jwt:
      secret-key: NGRmOTI3M2QyYjY2ZjY2NjYxZTE4MjY3YjlmYjE4ZGMxZjJkZDQ0YjdiZjM3OTFlN2M5Mjg3ZDYyYmEyMDIxZQ==
      expiration: 86400000

